CREATE DATABASE PENJUALAN_DVD;

USE PENJUALAN_DVD;

CREATE TABLE GENRE (
	ID_GENRE SMALLINT PRIMARY KEY,
	GENRE VARCHAR(45)
);

CREATE TABLE MOVIE (
	KODE_DVD VARCHAR(10) PRIMARY KEY,
	JUDUL VARCHAR(60),
	HARGA_SEWA DOUBLE,
	DENDA DOUBLE,
	TAHUN_RILIS SMALLINT
);

CREATE TABLE GENRE_MOVIE (
	ID_GENRE smallint,
	KODE_DVD VARCHAR(10),
	GENRE_MOVIE(ID_GENRE) REFERENCES GENRE(ID_GENRE),
	GENRE_MOVIE(KODE_DVD) REFERENCES MOVIE(KODE_DVD), 
	PRIMARY KEY (ID_GENRE,KODE_DVD)
);

CREATE TABLE KECAMATAN (
	ID_KECAMATAN SMALLINT PRIMARY KEY,
	KECAMATAN VARCHAR(45)
);

CREATE TABLE KELURAHAN (
	ID_KELURAHAN SMALLINT PRIMARY KEY,
	ID_KECAMATAN SMALLINT REFERENCES KECAMATAN(ID_KECAMATAN),
	KELURAHAN VARCHAR(45)
);

CREATE TABLE PELANGGAN (
	KODE_PELANGGAN VARCHAR(10) PRIMARY KEY,
	ID_KELURAHAN smallint, 
	PELANGGAN(ID_KELURAHAN) REFERENCES KELURAHAN(ID_KELURAHAN),
	NAMA VARCHAR(45),
	ALAMAT VARCHAR(60),
	JENIS_KELAMIN CHAR(1),
	CHECK (JENIS_KELAMIN IN ('P','L'))
);

CREATE TABLE KONTAK_PELANGGAN (
	NO_HP VARCHAR(25) UNIQUE,
	KODE_PELANGGAN VARCHAR(10), 
	kontak_pelanggan(kontak_pelanggan) REFERENCES PELANGGAN(KODE_PELANGGAN)
);

CREATE TABLE TRANSAKSI (
	KODE_DVD VARCHAR(10),
	KODE_PELANGGAN VARCHAR(10),
	TANGGAL_SEWA DATE,
	TANGGAL_WAJIB_KEMBALI DATE,
	TANGGAL_REALISASI_KEMBALI DATE,
	transaksi(KODE_DVD) REFERENCES MOVIE(KODE_DVD),
	transaksi(kontak_pelanggan) REFERENCES PELANGGAN(KODE_PELANGGAN) 
	PRIMARY KEY (KODE_DVD,KODE_PELANGGAN,TANGGAL_SEWA)
);

ALTER TABLE MOVIE MODIFY TAHUN_RILIS YEAR(4);